name: CI

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.16.0
      - run: npm ci
      - run: npm test

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.16.0
      - run: npm ci
      - run: npm test

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.16.0
      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install setuptools
        run: pip install setuptools
      - run: npm ci
      - run: npm test

  publish:
    needs: [windows, linux, macos]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 20.16.0
          registry-url: 'https://registry.npmjs.org'
      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - name: Bump version
        run: npx standard-version
      - name: Push changes
        run: git push --follow-tags origin master
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}